name: ESLint PR Check (All Changed Files)

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRT HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Debug changed files
        run: |
          echo "Changed files: $CHANGED_FILES"

      - name: Run ESLint on all changed files
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            echo "Running ESLint on all changed files:"
            echo "$CHANGED_FILES"
            echo "$CHANGED_FILES" | xargs npx eslint --max-warnings=0
          else
            echo "No files changed. Skipping ESLint."
          fi