# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: "**/*.js, **/*.jsx, **/*.ts, **/*.tsx"

      - name: Install ESLint
        run: |
          npm install eslint

      - name: Run ESLint on changed files
        run: |
            if [ -n "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
              npx eslint ${{ steps.changed-files.outputs.all_changed_files }}
            else
              echo "No changed JavaScript/TypeScript files to lint."
            fi
        continue-on-error: false
