name: ESLint Fix on Push

on:
  push:
    branches:
      - main
      - feat-eslint-merge

jobs:
  eslint-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRT HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run ESLint with auto-fix on changed files
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            echo "Running ESLint on changed files:"
            echo "$CHANGED_FILES"
            echo "$CHANGED_FILES" | xargs npx eslint --fix
          else
            echo "No files changed. Skipping ESLint."
          fi

      - name: Check for changes
        id: git-check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push fixes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "style: Auto-fix ESLint errors [skip ci]"
          git push