name: ESLint PR Check (Changed Files Only)

on:
  pull_request:
    branches:
      - main  # Replace with your default branch name (e.g., master, main, etc.)

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for `git diff` to work properly

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Get changed files
        id: changed-files
        run: |
          # Get the list of changed files in the PR
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRT HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Run ESLint on changed files
        run: |
          if [ -n "${{ steps.changed-files.outputs.files }}" ]; then
            echo "Running ESLint on changed files:"
            echo "${{ steps.changed-files.outputs.files }}"
            npx eslint ${{ steps.changed-files.outputs.files }}
          else
            echo "No files changed. Skipping ESLint."
          fi