name: Lint Changed Files on PR

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0  # Fetch full history to avoid "bad object" errors

    - name: Get base branch info
      run: |
        echo "BASE_REF=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
        echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV

    - name: Fetch base branch
      run: git fetch origin ${{ env.BASE_REF }} --depth=1

    - name: Get changed files
      id: changed-files
      run: |
        # Get list of changed files with allowed extensions
        CHANGED=$(git diff --name-only --diff-filter=ACMRT ${{ env.BASE_SHA }} ${{ github.sha }} | grep -E '\.(js|jsx|ts|tsx|mjs|cjs)$' || true)
        
        # Format for output
        if [ -z "$CHANGED" ]; then
          echo "No changed files detected"
          echo "CHANGED_FILES=" >> $GITHUB_ENV
        else
          echo "Changed files detected:"
          echo "$CHANGED"
          echo "CHANGED_FILES=${CHANGED}" >> $GITHUB_ENV
        fi

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run ESLint on changed files
      if: env.CHANGED_FILES != ''
      run: |
        echo "${{ env.CHANGED_FILES }}" | tr ' ' '\n' | xargs -I{} npx eslint "{}"